import type { FinishedProductData } from "@/features/clients/components/FinishedProduct/FinishedProducts";

export const FinishedProductsTableData: FinishedProductData[] = [
  {
    id: 1,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 2,
    name: "Qobul",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 3,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 4,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 5,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 6,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 7,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 8,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 9,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 10,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 11,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 12,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 13,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 14,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 15,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 16,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 17,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 18,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 19,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
  {
    id: 20,
    name: "Durioqshom",
    country: "Afgoniston",
    city: "Afgoniston",
    sections: "Готовая продукция",
  },
];