export const roleOptions = [
  { id: 2, name: "Аналитика" },
  { id: 3, name: "Администрация" },
  { id: 4, name: "Гатовая продукция" },
  { id: 5, name: "Склады" },
];

export const permOptions = [
  { id: 2, name: "Справочники" },
  { id: 3, name: "Аналитика" },
  { id: 4, name: "Администрация" },
  { id: 5, name: "Гатовая продукция" },
  { id: 6, name: "Склады" },
];

export const usersData = [
  {
    id: 1,
    fullName: "Alice Johnson",
    login: "alice.johnson@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234001",
    permissions: [{ id: 2, name: "Аналитика" }],
    userRoles: [{ id: 2, name: "Аналитика" }],
    last_activity: "08:15",
  },
  {
    id: 2,
    fullName: "Bob Smith",
    login: "bob.smith@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234002",
    permissions: [{ id: 3, name: "Администрация" }],
    userRoles: [{ id: 3, name: "Администрация" }],
    last_activity: "09:20",
  },
  {
    id: 3,
    fullName: "Charlie Brown",
    login: "charlie.brown@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234003",
    permissions: [{ id: 4, name: "Гатовая продукция" }],
    userRoles: [{ id: 4, name: "Гатовая продукция" }],
    last_activity: "10:45",
  },
  {
    id: 4,
    fullName: "Diana Prince",
    login: "diana.prince@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234004",
    permissions: [{ id: 5, name: "Склады" }],
    userRoles: [{ id: 5, name: "Склады" }],
    last_activity: "11:10",
  },
  {
    id: 5,
    fullName: "Ethan Hunt",
    login: "ethan.hunt@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234005",
    permissions: [
      { id: 2, name: "Аналитика" },
      { id: 3, name: "Администрация" },
    ],
    userRoles: [{ id: 2, name: "Аналитика" }],
    last_activity: "12:05",
  },
  {
    id: 6,
    fullName: "Fiona Gallagher",
    login: "fiona.gallagher@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234006",
    permissions: [
      { id: 3, name: "Администрация" },
      { id: 4, name: "Гатовая продукция" },
    ],
    userRoles: [
      { id: 3, name: "Администрация" },
      { id: 4, name: "Гатовая продукция" },
    ],
    last_activity: "13:30",
  },
  {
    id: 7,
    fullName: "George Martin",
    login: "george.martin@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234007",
    permissions: [{ id: 4, name: "Гатовая продукция" }],
    userRoles: [{ id: 4, name: "Гатовая продукция" }],
    last_activity: "14:50",
  },
  {
    id: 8,
    fullName: "Hannah Baker",
    login: "hannah.baker@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234008",
    permissions: [{ id: 5, name: "Склады" }],
    userRoles: [{ id: 5, name: "Склады" }],
    last_activity: "15:15",
  },
  {
    id: 9,
    fullName: "Ian Somerhalder",
    login: "ian.somerhalder@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234009",
    permissions: [
      { id: 2, name: "Аналитика" },
      { id: 5, name: "Склады" },
    ],
    userRoles: [{ id: 2, name: "Аналитика" }],
    last_activity: "16:40",
  },
  {
    id: 10,
    fullName: "Julia Roberts",
    login: "julia.roberts@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234010",
    permissions: [{ id: 3, name: "Администрация" }],
    userRoles: [
      { id: 3, name: "Администрация" },
      { id: 4, name: "Гатовая продукция" },
    ],
    last_activity: "17:55",
  },
  {
    id: 11,
    fullName: "Kevin Hart",
    login: "kevin.hart@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234011",
    permissions: [{ id: 4, name: "Гатовая продукция" }],
    userRoles: [
      { id: 2, name: "Аналитика" },
      { id: 3, name: "Администрация" },
    ],
    last_activity: "18:05",
  },
  {
    id: 12,
    fullName: "Laura Linney",
    login: "laura.linney@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234012",
    permissions: [{ id: 5, name: "Склады" }],
    userRoles: [
      { id: 4, name: "Гатовая продукция" },
      { id: 5, name: "Склады" },
    ],
    last_activity: "18:20",
  },
  {
    id: 13,
    fullName: "Michael Jordan",
    login: "michael.jordan@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234013",
    permissions: [{ id: 2, name: "Аналитика" }],
    userRoles: [
      { id: 2, name: "Аналитика" },
      { id: 3, name: "Администрация" },
    ],
    last_activity: "18:35",
  },
  {
    id: 14,
    fullName: "Natalie Portman",
    login: "natalie.portman@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234014",
    permissions: [{ id: 3, name: "Администрация" }],
    userRoles: [{ id: 4, name: "Гатовая продукция" }],
    last_activity: "18:50",
  },
  {
    id: 15,
    fullName: "Oscar Isaac",
    login: "oscar.isaac@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234015",
    permissions: [
      { id: 4, name: "Гатовая продукция" },
      { id: 5, name: "Склады" },
    ],
    userRoles: [{ id: 3, name: "Администрация" }],
    last_activity: "19:05",
  },
  {
    id: 16,
    fullName: "Penelope Cruz",
    login: "penelope.cruz@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234016",
    permissions: [{ id: 2, name: "Аналитика" }],
    userRoles: [
      { id: 2, name: "Аналитика" },
      { id: 4, name: "Гатовая продукция" },
    ],
    last_activity: "19:20",
  },
  {
    id: 17,
    fullName: "Quentin Tarantino",
    login: "quentin.tarantino@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234017",
    permissions: [{ id: 3, name: "Администрация" }],
    userRoles: [{ id: 3, name: "Администрация" }],
    last_activity: "19:35",
  },
  {
    id: 18,
    fullName: "Rachel McAdams",
    login: "rachel.mcadams@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234018",
    permissions: [{ id: 4, name: "Гатовая продукция" }],
    userRoles: [
      { id: 2, name: "Аналитика" },
      { id: 5, name: "Склады" },
    ],
    last_activity: "19:50",
  },
  {
    id: 19,
    fullName: "Samuel L. Jackson",
    login: "samuel.jackson@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234019",
    permissions: [{ id: 5, name: "Склады" }],
    userRoles: [{ id: 3, name: "Администрация" }],
    last_activity: "20:05",
  },
  {
    id: 20,
    fullName: "Tina Fey",
    login: "tina.fey@gmail.com",
    password: "pass123",
    phoneNumber: "+998901234020",
    permissions: [
      { id: 2, name: "Аналитика" },
      { id: 3, name: "Администрация" },
    ],
    userRoles: [{ id: 4, name: "Гатовая продукция" }],
    last_activity: "20:20",
  },
];
