export const routes = {
  HOME: "/",
  REGISTER: "/register",
  USERS: "/users",
  ROLES: "/roles",
  SUPERVISORS: "/supervisors",
  EVENTS: "/events",
  SORT: "/refs/grade-quality",
  AUTH: "/auth",
  CLINENTS: "/refs/clients",
  VERIFYPHONE: "/auth/verify-phone",
  PASSWORD: "/auth/forgot-password",
  PARAMETERS: "/refs/parameters",
  PARAMETERS_DETAIL: "/refs/parameters/:id",
};
