export interface MaterialsItem {
  id: number;
  priyceList: boolean;
  order: number;
  name: string;
  code: string;
  unit: string;
  type: string;
  materialKind: string;
  section?: string;
}

export const MaterialsDetailData: MaterialsItem[] = [
  {
    id: 1,
    priyceList: false,
    order: 0,
    name: "Decuner 28 WE/F 1",
    code: "FNNOCREPE B 15",
    unit: "Кг",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 2,
    priyceList: false,
    order: 0,
    name: "Decuner 28 WE/F 1",
    code: "FNNOCREPE B 15",
    unit: "Кг",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 3,
    priyceList: false,
    order: 1,
    name: "ProSoft TQ 230H",
    code: "FNNOTROL 6000",
    unit: "Кг / шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 4,
    priyceList: false,
    order: 1,
    name: "ProSoft TQ 230H",
    code: "FNNOTROL 6000",
    unit: "Кг / шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 5,
    priyceList: false,
    order: 2,
    name: "Целулоза 200 кг",
    code: "FNNOPAS 8850",
    unit: "Шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 6,
    priyceList: false,
    order: 2,
    name: "Целулоза 200 кг",
    code: "FNNOPAS 8850",
    unit: "Шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 7,
    priyceList: false,
    order: 0,
    name: "Decuner 28 WE/F 1",
    code: "FNNOCREPE B 15",
    unit: "Кг",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 8,
    priyceList: false,
    order: 1,
    name: "ProSoft TQ 230H",
    code: "FNNOTROL 6000",
    unit: "Кг / шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 9,
    priyceList: false,
    order: 2,
    name: "Целулоза 200 кг",
    code: "FNNOPAS 8850",
    unit: "Шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 10,
    priyceList: false,
    order: 0,
    name: "Decuner 28 WE/F 1",
    code: "FNNOCREPE B 15",
    unit: "Кг",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 11,
    priyceList: false,
    order: 1,
    name: "ProSoft TQ 230H",
    code: "FNNOTROL 6000",
    unit: "Кг / шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
  {
    id: 12,
    priyceList: false,
    order: 2,
    name: "Целулоза 200 кг",
    code: "FNNOPAS 8850",
    unit: "Шт",
    type: "Химикаты",
    materialKind: "Сырье и материалы",
    section: "Склад сырья",
  },
];
